// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBq95ohmnr3I3p55AUR0ahMRheHA_GBsNs',
    appId: '1:998253875556:web:f6572465b8a768097f2a71',
    messagingSenderId: '998253875556',
    projectId: 'instagram-clone-c6816',
    authDomain: 'instagram-clone-c6816.firebaseapp.com',
    storageBucket: 'instagram-clone-c6816.appspot.com',
    measurementId: 'G-19PZQV9ED7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXlAAtGGgJl23iRtxcQvEQN8ddG0L1wtA',
    appId: '1:998253875556:android:b95572c2ee5d1b4f7f2a71',
    messagingSenderId: '998253875556',
    projectId: 'instagram-clone-c6816',
    storageBucket: 'instagram-clone-c6816.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeNEuM4n8mY-jtJ2NVi-i72_qkIm0xy8o',
    appId: '1:998253875556:ios:9898d9c3ed549f867f2a71',
    messagingSenderId: '998253875556',
    projectId: 'instagram-clone-c6816',
    storageBucket: 'instagram-clone-c6816.appspot.com',
    iosBundleId: 'bhat.agu.instagramCloneFlutter',
  );
}
